#!/bin/bash
# Script to get private key for my-dev-account

ACCOUNT_NAME="my-dev-account"

echo "Method 1: Export from inferenced keyring (if key is already imported)"
echo "=========================================="
echo ""
echo "If your key is already in the keyring, run:"
echo ""
echo "  inferenced keys export $ACCOUNT_NAME --unarmored-hex --unsafe --keyring-backend test"
echo ""
echo "This will output a 64-character hex string."
echo ""
echo "---"
echo ""
echo "Method 2: Import from mnemonic first, then export"
echo "=========================================="
echo ""
echo "If the key is not in the keyring, first import it:"
echo ""
echo "  inferenced keys add $ACCOUNT_NAME --recover --keyring-backend test"
echo ""
echo "Then paste your mnemonic when prompted:"
echo "  fat charge sentence power daughter hope ability amazing gorilla couch scatter item soldier game like merit jaguar dream found jacket borrow humor voyage method"
echo ""
echo "Then export the private key:"
echo "  inferenced keys export $ACCOUNT_NAME --unarmored-hex --unsafe --keyring-backend test"
echo ""
